// File: integrations/ado/ado-repo-pusher.ts
import * as azdev from 'azure-devops-node-api';
import * as fs from 'fs';
import * as path from 'path';

// ---------------------------------------------------------------------------
// AdoRepoPusher
// ---------------------------------------------------------------------------
export class AdoRepoPusher {
  constructor(
    private readonly connection: azdev.WebApi,
    private readonly projectName: string
  ) {}

  /**
   * Create or update a single file in an ADO Git repository.
   * Commit message format: [AutoGen] TC-{id}: {testName} – generated by Claude Code
   * Returns the commitId of the push.
   */
  async pushFile(
    repoName: string,
    branch: string,
    filePath: string,
    content: string,
    commitMessage: string
  ): Promise<string> {
    const gitApi = await this.connection.getGitApi();

    const repo = await gitApi.getRepository(repoName, this.projectName);
    if (!repo?.id) {
      throw new Error(`Repository "${repoName}" not found in project "${this.projectName}"`);
    }

    // Check whether the file already exists to determine changeType and oldObjectId
    let oldObjectId = '0000000000000000000000000000000000000000';
    let changeType: number = 1; // 1 = Add

    try {
      const existingItems = await gitApi.getItems(
        repo.id,
        this.projectName,
        filePath,
        undefined,
        undefined,
        undefined,
        true
      );
      if (existingItems && existingItems.length > 0 && existingItems[0].objectId) {
        oldObjectId = existingItems[0].objectId;
        changeType = 2; // 2 = Edit
      }
    } catch {
      // File does not exist — keep defaults (Add + zero hash)
    }

    // Get current branch tip to use as oldObjectId for the refUpdate
    let branchOldObjectId = '0000000000000000000000000000000000000000';
    try {
      const refs = await gitApi.getRefs(repo.id, this.projectName, `heads/${branch}`);
      if (refs && refs.length > 0 && refs[0].objectId) {
        branchOldObjectId = refs[0].objectId;
      }
    } catch {
      // Branch may not exist yet — create with zero hash
    }

    const push = await gitApi.createPush(
      {
        refUpdates: [
          { name: `refs/heads/${branch}`, oldObjectId: branchOldObjectId },
        ],
        commits: [
          {
            comment: commitMessage,
            changes: [
              {
                changeType,
                item: { path: `/${filePath.replace(/^\//, '')}` },
                newContent: {
                  content,
                  contentType: 0, // RawText
                },
              },
            ],
          },
        ],
      } as unknown as Parameters<typeof gitApi.createPush>[0],
      repo.id,
      this.projectName
    );

    const commitId = push?.commits?.[0]?.commitId;
    if (!commitId) {
      throw new Error(`Push succeeded but no commitId returned for file: ${filePath}`);
    }

    return commitId;
  }

  /**
   * Push all .ts files in a local directory (recursively) to a remote directory in the repo.
   */
  async pushDirectory(
    repoName: string,
    branch: string,
    localDir: string,
    remoteDir: string
  ): Promise<void> {
    const files = this.collectTsFiles(localDir);

    if (files.length === 0) {
      console.warn(`No .ts files found in: ${localDir}`);
      return;
    }

    for (const localFile of files) {
      const relPath = path.relative(localDir, localFile).replace(/\\/g, '/');
      const remotePath = `${remoteDir.replace(/\/$/, '')}/${relPath}`;
      const content = fs.readFileSync(localFile, 'utf8');
      const commitMessage = `[AutoGen] Push ${relPath} – generated by Claude Code`;

      const commitId = await this.pushFile(repoName, branch, remotePath, content, commitMessage);
      console.log(`  Pushed: ${remotePath} → commit ${commitId}`);
    }
  }

  /**
   * Create a pull request from sourceBranch to the default (main) branch.
   * Returns the PR id.
   */
  async createPullRequest(
    repoName: string,
    sourceBranch: string,
    title: string,
    description: string
  ): Promise<number> {
    const gitApi = await this.connection.getGitApi();

    const repo = await gitApi.getRepository(repoName, this.projectName);
    if (!repo?.id) {
      throw new Error(`Repository "${repoName}" not found in project "${this.projectName}"`);
    }

    // Determine target branch (default: main, fallback: master)
    let targetBranch = 'main';
    try {
      const refs = await gitApi.getRefs(repo.id, this.projectName, 'heads/main');
      if (!refs || refs.length === 0) {
        const masterRefs = await gitApi.getRefs(repo.id, this.projectName, 'heads/master');
        if (masterRefs && masterRefs.length > 0) {
          targetBranch = 'master';
        }
      }
    } catch {
      targetBranch = 'main';
    }

    const pr = await gitApi.createPullRequest(
      {
        title,
        description,
        sourceRefName: `refs/heads/${sourceBranch}`,
        targetRefName: `refs/heads/${targetBranch}`,
        isDraft: false,
      } as unknown as Parameters<typeof gitApi.createPullRequest>[0],
      repo.id,
      this.projectName
    );

    if (!pr?.pullRequestId) {
      throw new Error(`Pull request creation returned no ID`);
    }

    return pr.pullRequestId;
  }

  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------

  private collectTsFiles(dir: string): string[] {
    const results: string[] = [];
    if (!fs.existsSync(dir)) return results;

    const entries = fs.readdirSync(dir);
    for (const entry of entries) {
      const fullPath = path.join(dir, entry);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        results.push(...this.collectTsFiles(fullPath));
      } else if (entry.endsWith('.ts')) {
        results.push(fullPath);
      }
    }

    return results;
  }
}
